### ISSUE TITLE
G4 v11.2 Support

### ISSUE THREAD

**Issue by TomGoffrey** [QTNM/QTNMSim#13]
In G4 11.2 the signature for G4VIntegrationDriver::OnComputeStep has changed:

```
$ diff geant/geant4-v11.2.0-install/include/Geant4/G4VIntegrationDriver.hh geant/geant4-v11.1.0-install/include/Geant4/G4VIntegrationDriver.hh
49c49
< #include "G4EquationOfMotion.hh"
---
> #include "G4MagIntegratorStepper.hh"
51,52d50
< class G4MagIntegratorStepper;
<
78c76
<     virtual void OnComputeStep(const G4FieldTrack* /*track*/ = nullptr) = 0;
---
>     virtual void OnComputeStep() = 0;
```

which means that the implementation of QTBorisDriver::OnComputeStep hides the base class function rather than override. I suspect, given the commented line 101 in QTBorisDriver.hh, this is a known issue...are we not supporting G4 v11.2/is there a proposed workaround?

**Comment by yramachers** [comment]
I didn't think of G4 11.2 so far, thanks for pointing that out. At the time of the last tag, there was no support for 11.2 on the CERN environment, the cvmfs environments, I mean. That has changed on December 26, it seems, with LCG_105 now available.
Slightly annoying, this apparent backward compatibility break. Nevertheless, we are in pre-production hence changing code to follow the latest external release is fine for a new tag.

**Comment by yramachers** [comment]
Ok, just tried it, all fine. It needs a single line change to compile: line 101 in QTBorisDriver.hh uncomment, and comment line 102, done.
That line 101 came straight from the Geant4 original code hence I assume they were planning/preparing that change already in version 11.1.
With that single line change, all compiles fine on 11.2. I've got the branch and could send a pull request but it isn't really urgent right now hence may wait a little longer.

**Comment by TomGoffrey** [comment]
Just to add the conclusion of our discussion earlier - the agreed preference is to move to v11.2 rather than attempt any form of backwards compatibility. Low priority for now though.
